# Generated by Django 5.2.6 on 2026-09-01 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=80)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation_m', models.IntegerField(default=0)),
                ('distance_to_river_m', models.FloatField(default=0)),
                ('landcover', models.CharField(blank=True, choices=[('Wetland', 'Wetland'), ('Agriculture', 'Agriculture'), ('Forest', 'Forest'), ('Urban', 'Urban'), ('Plantation', 'Plantation'), ('Bare Soil', 'Bare Soil'), ('Scrub', 'Scrub')], max_length=20)),
                ('soil_type', models.CharField(blank=True, choices=[('Loamy', 'Loamy'), ('Clay', 'Clay'), ('Silty', 'Silty'), ('Sandy', 'Sandy'), ('Peaty', 'Peaty')], max_length=20)),
                ('water_supply', models.CharField(blank=True, choices=[('Municipal', 'Municipal'), ('Well', 'Well'), ('Surface water', 'Surface water'), ('Rainwater harvesting', 'Rainwater harvesting'), ('Tube-well', 'Tube-well')], max_length=30)),
                ('electricity', models.CharField(blank=True, choices=[('Grid', 'Grid'), ('Mixed', 'Mixed'), ('Off-grid (solar)', 'Off-grid (solar)')], max_length=20)),
                ('road_quality', models.CharField(blank=True, choices=[('Good (paved)', 'Good (paved)'), ('Fair', 'Fair'), ('Poor (unpaved)', 'Poor (unpaved)'), ('No road access', 'No road access')], max_length=20)),
                ('urban_rural', models.CharField(blank=True, choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=10)),
                ('population_density_per_km2', models.IntegerField(default=0)),
                ('built_up_percent', models.FloatField(default=0)),
                ('infrastructure_score', models.IntegerField(default=0, help_text='0-100, higher is better')),
                ('nearest_hospital_km', models.FloatField(default=0)),
                ('nearest_evac_km', models.FloatField(default=0)),
                ('is_good_to_live', models.BooleanField(default=True)),
                ('reason_not_good_to_live', models.CharField(blank=True, max_length=255)),
                ('current_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['district', 'name'],
                'indexes': [models.Index(fields=['district'], name='flood_locat_distric_2617c3_idx'), models.Index(fields=['current_risk_level'], name='flood_locat_current_275ee1_idx')],
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.CreateModel(
            name='FloodAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='flood.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(blank=True, db_index=True, max_length=30)),
                ('date', models.DateField()),
                ('rainfall_7d_mm', models.FloatField(help_text='Rainfall over the last 7 days (mm)')),
                ('monthly_rainfall_mm', models.FloatField(help_text='Rainfall over the last month (mm)')),
                ('drainage_index', models.FloatField(help_text='0 (poor) - 1 (excellent) drainage capacity')),
                ('ndvi', models.FloatField(help_text='Normalized Difference Vegetation Index')),
                ('ndwi', models.FloatField(help_text='Normalized Difference Water Index')),
                ('water_presence_flag', models.BooleanField(default=False)),
                ('historical_flood_count', models.PositiveSmallIntegerField(default=0)),
                ('flood_risk_score', models.FloatField(help_text='0-100 continuous risk score')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('flood_occurrence', models.BooleanField(default=False)),
                ('inundation_area_sqm', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='flood.location')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='flood_flood_date_7ec4b0_idx')],
            },
        ),
    ]
